[package]
name = "abc162"
version = "0.1.0"
authors = ["eda3 <gerorin1010@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "0.4.1"

[profile.release]
lto = true
panic = 'abort'
